@startuml
!pragma layout smetana
'https://plantuml.com/object-diagram

object Main
object Controller
object Adventure
object Creature
object Player
object ActionPoint
object Item
object Consumable
object Equipment
object Weapon

package "util"{
object TextUI
object FileIO
object DatabaseManager
}


Main -down-> Adventure
Main -right-> Controller
Adventure -left-> Player
Adventure -down-> ActionPoint
Adventure --> Creature
Controller -right-> "util"
Item -left-> ActionPoint
Item -right-> Consumable
Item --> Equipment
Equipment --> Weapon


@enduml
